version: '2'
services:
  redis:
    image: "redis:alpine"
  postgres:
    image: "postgres:10.4"
    environment:
     POSTGRES_PASSWORD: password
     POSTGRES_USER: postgres
  web:
    build: .
    ports:
     - "80:7777"
    volumes:
     - .:/usr/src/app
    depends_on:
      - postgres
      - redis
    command: ["./wait_for_it.sh", "postgres:5432", "--", "npm", "start"]
