# docker-compose.yml
version: "3"
services:
  app:
    build: .
    depends_on:
      - db
      - redis
    links:
      - db
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: users-microservice
      DB_HOST: db
  db:
    image: postgres:10.4-alpine
    expose:
      - "5432"
    ports:
      - "15432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: users-microservice
  redis:
    image: redis
