version: '3'
services:
  api:
    build: .
    depends_on:
      - postgresql
    ports:
      - "3334:3334"
    environment:
      - PORT=3334
      - DB_HOST=postgresql
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    volumes:
      - ./src:/home/app/src
  postgresql:
    image: postgres:12.0-alpine
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: users-microservice

  redis:
    image: redis
